FROM ruby:3.3.6

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

# 必要なパッケージをインストール
RUN apt-get update -qq \
&& apt-get install -y ca-certificates curl gnupg build-essential libpq-dev nodejs yarn vim \
&& mkdir -p /etc/apt/keyrings \
&& curl -fsSL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor -o /etc/apt/keyrings/yarn.gpg \
&& echo "deb [signed-by=/etc/apt/keyrings/yarn.gpg] https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
&& apt-get update -qq && apt-get install -y yarn

# アプリケーション用のディレクトリを作成
RUN mkdir /myapp
WORKDIR /myapp

# 必要なGemとNode.jsパッケージをインストール
COPY Gemfile* /myapp/
RUN gem install bundler && bundle install
COPY package.json yarn.lock /myapp/
RUN yarn install

# ソースコードをコピー
COPY . /myapp

# アセットをプリコンパイル
RUN bundle exec rails assets:precompile
